robot_backend: tianji_wuji_host
robot_ip: 192.168.8.166

left_hand_serial: 387D365B3533
right_hand_serial: 3860364D3533

tianji_sdk_root: /home/user/workspace/dexproj_backup/DexProj_back_up_0602/wuji-hand-teleop/src/output_devices/tianji_output
tianji_config_path: /home/user/workspace/dexproj_backup/DexProj_back_up_0602/wuji-hand-teleop/src/output_devices/tianji_output/tianji_output/config/ccs_m6.MvKDCfg

camera:
  - head:realsense:254322070127
  - left_wrist:realsense:260522279497
  - right_wrist:realsense:260522272600

camera_width: 424
camera_height: 240
camera_capture_fps: 60
camera_fps: 30
max_camera_age_ms: 150
camera_warmup_sec: 3

policy_host: 127.0.0.1
policy_port: 5555
policy_timeout_ms: 15000

task: pick up the bottle
execution_horizon: 16
duration: 0.05

freeze_left_side: true
freeze_left_use_current: true

auto_start: true
no_keyboard: true
max_chunks: 200

ros2_publish_jointstate: true
arm_interpolation_hz: 200
arm_interpolation_mode: cubic
